#!/bin/bash

output=$( which sginfo )

if [ -z "$output" ]
then
    # prompt install of sg3_utils
    echo "Package sg3-utils (sg3_utils, on some distros) not installed! Install it before proceeding."
    exit
    
else
    # continue on
    echo "LF Tools v1.0"
    echo "--------------------------"
fi

while getopts :mlxh OPTION
do
    case $OPTION in
        m)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C2 00 00 00 00 00 00 00 00 00
            ;;
        l)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C1 00 00 00 00 00 00 00 00 00
            ;;
        x)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C6 00 00 00 00 00 00 00 00 00
            ;;
        h)
            echo "LFTools Usage:"
            echo "-m: mount"
            echo "-l: lock"
            echo "-x: eject"
            echo "-h: help"
    esac
done
