#!/bin/bash

output=$( which sginfo )

if [ -z "$output" ]
then
    # prompt install of sg3_utils
    echo "Package sg3-utils (sg3_utils, on some distros) not installed! Install it before proceeding."
    exit
    
else
    # continue on
    echo "LF Tools"
    echo "--------------------------"
fi

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="LF Tools v1.0 (press Control+C to quit)"
TITLE="LF Tools Menu"
MENU="Choose an option from the list here:"

OPTIONS=(1 "Mount Device"
         2 "Lock Device"
         3 "Eject Device")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C2 00 00 00 00 00 00 00 00 00
            ;;
        2)  
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C1 00 00 00 00 00 00 00 00 00
            ;;
        3)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C6 00 00 00 00 00 00 00 00 00
            ;;
esac
