#!/bin/bash

output=$( which sginfo )

if [ -z "$output" ]
then
    # prompt install of sg3_utils
    echo "Package sg3-utils (sg3_utils, on some distros) not installed! Install it before proceeding."
    exit
    
else
    # continue on
    echo "LF Tools"
    echo "--------------------------"
fi

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="LF Tools (press Control+C to quit)"
TITLE="LF Tools Menu"
MENU="Choose an option from the list here:"

OPTIONS=(1 "Mount Device"
         2 "Lock Device"
         3 "Eject Device"
         4 "Update Didj")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C2 00 00 00 00 00 00 00 00 00
            ;;
        2)  
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C1 00 00 00 00 00 00 00 00 00
            ;;
        3)
            echo "Find your Leapster2/Didj, and enter the path. (e.g. /dev/sg3)"
            sudo sg_scan -i
            echo -n "Path: "
            read -r lfdevpath
            sudo sg_raw $lfdevpath C6 00 00 00 00 00 00 00 00 00
            ;;
        4)
            echo "You need to mount your Didj before proceeding."            
            echo "You are about to do something potentially dangerous to your Didj."
            echo "Make sure you have full batteries, (or be plugged into AC power) and run this."
            echo "Do you wish to continue?"
            echo -n "y/N: "
            read -r updatec
            if [ "$updatec" = 'n' ] || [ "$updatec" = '' ]
            then
                # cancel update
                echo "Update cancelled."
                exit
            else
                # continue update
                echo "Updating now..."
                curl -O https://file.garden/YtxRl-gHkWVkfPs7/Firmware/DidjFirmware.zip
                unzip -q ./DidjFirmware.zip
                rm ./DidjFirmware.zip
                echo "Now sending update to Didj. Please wait..."
                cp -r ./firmware-LF_LF1000/ /media/$USER/Didj/Base/
                echo "Done. Waiting about 30 seconds for the Didj to recognize the update."
                sleep 30
                echo "Ejecting now. Update completed."
                rm -rf ./firmware-LF_LF1000/
                sudo sg_raw $lfdevpath C6 00 00 00 00 00 00 00 00 00
                exit
            fi
            ;;
esac
